<?php

namespace App\Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use App\Models\AbstractIblockPropertyValuesTable;

class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
  public const IBLOCK_ID = 16;

  public static function getMap(): array
  {
    $map = [
      'procedure' => new ReferenceField(
        'procedure',
        DocProcedurePropertyValuesTable::class,
        ['=this.procedure_ID' => 'ref.IBLOCK_ELEMENT_ID']
      ),
    ];

    return parent::getMap() + $map; // TODO: Change the autogenerated stub

  }
}
